

[options]
    app_id = 'wx3cf0f39249eb0exxx'
    secret  = 'f1c242f4f28f735d4687abb469072xxx'
    token     = 'wego'
    [options.log]
        level = 'debug'
        file  = '/tmp/easywechat.log'


