[system]
    debug = true
    use_cache = true

[system.log]
    level = 'debug'
    file = 'logs/wechat.log'


[domain]
       [domain.host]
            url = 'https://mp.quick58.com'
        [domain.default]
#https://apihk.mch.weixin.qq.com/pay/unifiedorder    （建议接入点：东南亚）
#https://apius.mch.weixin.qq.com/pay/unifiedorder    （建议接入点：其它）
#https://api.mch.weixin.qq.com/pay/unifiedorder        （建议接入点：中国国内）
#注：商户可根据实际请求情况选择最优域名进行访问，建议在接入时做好兼容，当访问其中一个域名出现异常时，可自动切换为其他域名。
            url = 'https://api.mch.weixin.qq.com'
        [domain.official_account]
#通用域名(api.weixin.qq.com)，使用该域名将访问官方指定就近的接入点；
#上海域名(sh.api.weixin.qq.com)，使用该域名将访问上海的接入点；
#深圳域名(sz.api.weixin.qq.com)，使用该域名将访问深圳的接入点；
#香港域名(hk.api.weixin.qq.com)，使用该域名将访问香港的接入点。
            url = 'https://api.weixin.qq.com'

[official_account]
#        [official.config]
#            data_type = "json"
        [official_account.sandbox]
            app_id ='wx1ad61aeef1903b93'
            secret = 'c96956c2fd5ce7bfd7a0db1f7679ff6d'
#            1	牛排	o5jo6s6M67vRRRcfmnXNkvUplIgc	移除
#            2	moto	o5jo6sy4lPrEPfORJV_BPd3caL9Y	移除
#            3	聪神不是神	o5jo6s3RZ6rxuVAW33IpTjYWQOg4	移除
#            4	Patrick	o5jo6syEsFrBQ5rSl1p973vm3sgk	移除
        [official_account.default]
#            app_id ='wxbafed7010e0f4531'                    #AppID
#            secret = '62dfc98746e2c4073ba4938574801097'     #AppSecret
             app_id ='wx15810ca16324c225'                      #AppID
             secret = '4f2601f6567ac4b5741aa2dc2e5eadfd'       #AppSecret
             token = 'golang_develop_godcong'                              #Token
             aes_key = 'DbWPitkfiWkhLwDPA48laxJojyiNqVwtK7R1ENPvEwC'      #EncodingAESKey
        [official_account.default.http]
            time_out = 5
            keep_alive = 30

        [official_account.default.oauth]
            scopes   = ['snsapi_userinfo']
            redirect_uri ="/oauth_callback"

[open_platform]
        [open_platform.default]
            app_id ='wx426b3015555a46be'                      #AppID
            secret = '7813490da6f1265e4901ffb80afaa36f'       #AppSecret
            token = 'your-token'                              #Token
            aes_key = ''                                      #EncodingAESKey

[mini_program]
        [mini_program.default]
#            app_id ='wx426b3015555a46be'                      #AppID
#            secret = '7813490da6f1265e4901ffb80afaa36f'       #AppSecret
                app_id ='wx1ad61aeef1903b93'                      #AppID
                secret = 'c96956c2fd5ce7bfd7a0db1f7679ff6d'       #AppSecret
                token = 'godcong'                              #Token
                aes_key = 'O9aVVkSTmgJK4qSibhSYpGQzRbZ2NQSJ'      #EncodingAESKey

[payment]
        [payment.default]
            sandbox = false
            app_id ='wx15810ca16324c225'
            mch_id = '1516796851'
            key = 'aTKnSUcTkbEnhwQNdutWkQxAjnhAz2jK'
            notify_url ='https://mp.quick58.com/charge/callback'
            cert_path = 'cert/apiclient_cert.pem'
            key_path = 'cert/apiclient_key.pem'
            rootca_path = 'cert/rootca.pem'
            pubkey_path = "cert/publickey.pem"
            prikey_path = "cert/privatekey.pem"
        [payment.default.http]
            time_out = 5
            keep_alive = 30

[work]
        [work.default]
            corp_id = 'xxxxxxxxxxxxxxxxx'
            agent_id = 100020
            secret  = ''
